{{- if and .Values.persistence.dataDir.enabled (not .Values.persistence.dataDir.existingClaim ) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "quake-kube.fullname" . }}-assets
  labels:
{{- include "quake-kube.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.persistence.annotations  }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataDir.Size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
