apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "quake-kube.labels" . | nindent 4 }}
data:
  config.yaml: |
    fragLimit: {{ .Values.quakeServer.fragLimit }}
    timeLimit: {{ .Values.quakeServer.timeLimit }}
    bot:
      minPlayers: {{ .Values.quakeServer.bot.minPlayers }}
    game:
      motd: {{ .Values.quakeServer.game.motd }}
      type: {{ .Values.quakeServer.game.type }}
      forceRespawn: {{ .Values.quakeServer.game.forceRespawn }}
      inactivity: {{ .Values.quakeServer.game.inactivity }}
      quadFactor: {{ .Values.quakeServer.game.quadFactor }}
      weaponRespawn: {{ .Values.quakeServer.game.weaponRespawn }}
      singlePlayerSkill: {{ .Values.quakeServer.game.singlePlayerSkill }}
    server:
      hostname: {{ .Values.quakeServer.server.hostname }}
      maxClients: {{ .Values.quakeServer.server.maxClients }}
      password: {{ .Values.quakeServer.server.password }}
    commands:
  {{- with .Values.quakeServer.commands  }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
    maps:
  {{- with .Values.quakeServer.maps  }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
