apiVersion: v1
kind: Service
metadata:
  name: {{ include "quake-kube.fullname" . }}
  labels:
    {{- include "quake-kube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: 8080
      nodePort: 30001
      name: client
    - port: {{ .Values.service.serverPort }}
      targetPort: 27960
      nodePort: 30003
      name: server
    - port: {{ .Values.service.contentPort }}
      targetPort: 9090
      nodePort: 30002
      name: content
  selector:
    {{- include "quake-kube.selectorLabels" . | nindent 4 }}
